/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Charsets;
import com.google.common.hash.HashFunction;
import com.google.common.hash.HashCode;
import com.google.common.hash.Hashing;

public class HelloOtus {
    public static void main(String[] args) {
        HashFunction hf = Hashing.adler32();
        long id = 2;
        CharSequence name = "Vladislav";
        HashCode hc = hf.newHasher()
                .putLong(id)
                .putString(name, Charsets.UTF_8)
                .hash();
        System.out.println("Hash is " + hc);
    }
}
